- hosts: dev_env
  become: true
  user: vagrant
  vars:
    vagrant_home: "/home/vagrant" 
  enviroment:
    PATH: "$HOME/.nodenv/bin:$PATH"
  tasks:
    - name: install packages zsh
      yum: name=zsh update_cache=yes

    - name: install packages git  
      yum: name=git update_cache=yes
    
    - name: install packages git-core
      yum: name=git-core update_cache=yes
    
    - name: install nodenv binary
      git: repo=https://github.com/nodenv/nodenv.git
        dest={{ vagrant_home }}/.nodenv
        version=master
    
    - name: init nodenv
      command: ~/.nodenv/bin/nodenv init
    
    - name: update nodenv
      command: nodenv update
    
    - name: create nodenv plugin directory
      command: mkdir {{ vagrant_home }}/.nodenv/plugins
    
    - name: install node-build
      command: git clone https://github.com/nodenv/node-build.git {{ vagrant_home }}/.nodenv/plugins/node-build
